### ISSUE TITLE
requirement.txt and report an issue 

### ISSUE THREAD

**Issue by MahdiMohseni0033** [Ji4chenLi/t2v-turbo#5]
Hi thanks for your amazing work, I wanted to ask you something and report a problem, regarding to first one, is it possible to provide a requirement.txt file for your project, without it, it is very hard to find exact version of required libraries 
and second one is following error which I faced during the execution :
```
AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
Traceback (most recent call last):
  File "/home/ubuntu/Projects/t2v-turbo/app.py", line 191, in <module>
    pretrained_t2v = load_model_checkpoint(pretrained_t2v, args.base_model_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Projects/t2v-turbo/utils/common_utils.py", line 383, in load_model_checkpoint
    load_checkpoint(model, ckpt, full_strict=True)
  File "/home/ubuntu/Projects/t2v-turbo/utils/common_utils.py", line 375, in load_checkpoint
    state_dict = torch.load(ckpt, map_location="cpu")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/t2v-turbo/lib/python3.11/site-packages/torch/serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/t2v-turbo/lib/python3.11/site-packages/torch/serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by Ji4chenLi** [comment]
Hi,

Sorry for the inconvenience. Can you first make sure if all model checkpoints are correctly downloaded?

**Comment by GARV-k** [comment]
Same problem on my side. I am trying to inference on  colab btw. Please Help out with a  fix

**Comment by Ji4chenLi** [comment]
Hi @GARV-k ,

Could you share detailed error messages and ensure the checkpoints are correctly downloaded?

**Comment by GARV-k** [comment]
I downloaded the ckpt file again and tried again. It worked ! Although I am still not able to generate vids. 
the only change I made in app.py is : 
examples = ["A black baby bear walking on some rocks"] and 
root_path = "/content/drive/MyDrive/Turbo/t2v-turbo"

because I am using colab. 

and the output is : (no videos are generated, as far as I have checked. )
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
0it [00:00, ?it/s]
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
2024-06-08 21:25:45.381698: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-08 21:25:45.381751: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-08 21:25:45.512145: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-08 21:25:45.770062: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-08 21:25:47.872033: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
^C

**Comment by Ji4chenLi** [comment]
I'm sorry for not getting back to you sooner. It should be an issue with Google Colab, which is beyond the scope of our project.

I would recommend trying to use some colab alternatives, e.g., https://lightning.ai/studios.
